### PR TITLE
feat(app): support daemon mode on non-Windows platforms

### PR DESCRIPTION
**Pull request by skrashevich**
Added a new command-line flag `-daemon` to run the application in the background as a daemon. This option is only available for non-Windows operating systems due to platform-specific process handling. When enabled, the application restarts itself with the same arguments except for the `-daemon` flag, prints the PID of the background process, and then exits the current process.

Simplified replacement for #440

### CODE REVIEW

**Comment by skrashevich** [comment]
Why doubt?

**Comment by AlexxIT** [comment]
Why not use simple & symbol?

**Comment by skrashevich** [comment]
> Why not use simple & symbol?

These are completely different things. `&` is a shell function, not a kernel.

For example, a background process started by `&` will not stay alive after the shell session is closed

**Review by AlexxIT — APPROVED** [review]

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.0

**Pull request merged**
