### PR TITLE
fix(clipboard): fix copy to clipboard functionality

### PR DESCRIPTION
**Pull request by skrashevich**
Added a `copyTextToClipboard` function to handle text copying across different browsers and fallback scenarios. This function utilizes the Clipboard API when available, providing an asynchronous method to copy text securely. For browsers where the Clipboard API is not available or the page is not served over a secure context, a fallback method using a temporary textarea element and `document.execCommand` is employed. Replaced direct use of `navigator.clipboard.writeText` with this function in the 'shareget' click event listener to enhance cross-browser support and error handling.

### CODE REVIEW

**Comment by skrashevich** [comment]
> added the [doubt](https://github.com/AlexxIT/go2rtc/labels/doubt)  label [7 hours ago](https://github.com/AlexxIT/go2rtc/pull/878#event-12563219471)

reason?

**Comment by AlexxIT** [comment]
What browsers has problems with one line clipboard function?

**Comment by skrashevich** [comment]
> What browsers has problems with one line clipboard function?

[Safari on non-https pages](https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/) and [Firefox](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write#browser_compatibility)

**Review by AlexxIT — APPROVED** [review]

**Comment by AlexxIT** [comment]
Thanks!

**Pull request merged**
