### PR TITLE
Refactor docker image and ci

### PR DESCRIPTION
**Pull request by felipecrs**
Lots of changes, I don't even remember all, but some are:

1. Reduce image size:

```console
$ docker images
REPOSITORY                                                          TAG              IMAGE ID       CREATED         SIZE
ghcr.io/felipecrs/go2rtc                                            latest           8bc71224401e   4 minutes ago   188MB
alexxit/go2rtc                                                      latest           f3c41b944bd3   6 hours ago     249MB
```

2. Upgrade and pin go version, from 1.18.6 (latest from Alpine repos) to 1.19.2
3. Pin ngrok version to 3.1.0
4. Upgrade base image to the community version and pin it to 9.0.1, which provides a variant which comes with Python preinstalled
5. Build go2rtc from the same revision as the Dockerfile instead of latest main branch.
6. Refactor service call to make it look like the rest of the add-ons, like the SSH and VSCode ones. Let S6-Overlay and add-on watchdog handle restarts.

I'd be happy to clarify any change I made.

### CODE REVIEW

**Comment by felipecrs** [comment]
I don't know where your existing build script is, but it should work as it's working today, except that you may need to change the folder where it builds from `build/hassio` to `.` (the repository root).

**Comment by felipecrs** [comment]
I built an image out of it for testing, and you can use it to test too:

```console
docker pull ghcr.io/felipecrs/go2rtc:latest
```

**Comment by felipecrs** [comment]
I have been using this ever since, no issues observed.

**Comment by AlexxIT** [comment]
To many changes. Different base image. I need to test everything carefully myself. I don't have time right now, I'm working on another project. I like a lot of your changes, but not all of them :)

Now images building automatically by github after new tag
https://github.com/AlexxIT/go2rtc/blob/master/.github/workflows/builder.yml

**Comment by felipecrs** [comment]
Alright, I'm happy to revert whatever you dislike.

**Comment by felipecrs** [comment]
I fixed the builder.yaml to follow the changes as well. Tested, and it's working.

**Comment by felipecrs** [comment]
I will stop using hassio addon as base.

**Comment by felipecrs** [comment]
@AlexxIT the image is now based on the official Python alpine base image.

This is the new sizes comparison:

175MB (with this PR) vs 250MB (0.1-rc.3)

It now also comes with tini, for properly handling the signals.

**Comment by felipecrs** [comment]
I now also refactored the ci workflow so it runs on more events, and uses the latest pattern for building multi-platform images and tagging, based on https://github.com/docker/metadata-action#semver.

Home Assistant itself has started to refactor their pipelines to it, see:

https://github.com/hassio-addons/workflows/blob/main/.github/workflows/addon-ci.yaml#L173

Also, @AlexxIT, I would recommend stop publishing to docker hub and publish to ghcr.io instead, i.e.:

```
ghcr.io/alexxit/go2rtc
```

This simplifies the maintenance of the image since you don't have to maintain 2 accounts, and simplify the forking process because we can then build and push according to the owner of the repo. 

Home Assistant, Frigate, and many more has adopted ghcr.io over dockerhub as well:

https://github.com/hassio-addons/addon-ssh/blob/main/ssh/build.yaml#L3

**Comment by NickM-27** [comment]
To be clear frigate didn't adopt ghcr over dockerhub. Releases will be published to both.

**Comment by felipecrs** [comment]
Oh, that's true. I made a wrong assumption. The Frigate add-on continues to use DockerHub:

https://github.com/blakeblackshear/frigate-hass-addons/blob/80879183cb4040e4152bb56d805f2387e24ec884/frigate/config.yaml#L8

**Comment by felipecrs** [comment]
Anyway, let's not switch to ghcr.io in this PR if accepted. It can be done in a later PR.

**Comment by felipecrs** [comment]
@AlexxIT is what you don't like in this PR the fact that it does not download your previously built binaries? If so, let me know. I think I have an elegant solution for this problem.

**Comment by AlexxIT** [comment]
I'll look carefully on your image after release 1.0 version.
Main task for release - update WebRTC Camera integration.

**Comment by felipecrs** [comment]
No problem at all!

> Main task for release - update WebRTC Camera integration.

Oh, is this about using https://github.com/AlexxIT/webrtc as consumer of go2rtc?

**Comment by AlexxIT** [comment]
Yes. This described in FAQ

**Comment by felipecrs** [comment]
@AlexxIT ops, sorry, I was fixing the conflict at the same time as you!

**Comment by AlexxIT** [comment]
Do you know how to run this ffmpeg on alpine? https://github.com/BtbN/FFmpeg-Builds
Or we need to change OS. Because default ffmpeg doesn't support Hardware enc/dec.

**Comment by AlexxIT** [comment]
Well. Latest version very nice. Can you describe:

1. `push: branches: - 'master'` will build image on every commit? What tag it would have?
2. `pull_request: branches: - 'master'` why this? Also what do checks `github.event_name != 'pull_request'`?

I thinks we need try to change image to `python:slim-bullseye` and use https://github.com/BtbN/FFmpeg-Builds

And looks like I need to reinstall HassOS on mine Raspberry Pi 3 from arm to arm64 version for support this custom ffmpeg.

**Comment by felipecrs** [comment]
> 1. `push: branches: - 'master'` will build image on every commit? What tag it would have?

Yes, will build **and push** on every commit to `master` branch. Tag will be `master`, only.

> 2. `pull_request: branches: - 'master'` why this? Also what do checks `github.event_name != 'pull_request'`?

Means to build the image on every PR that targets `master` branch. The check you mention ensures the image does NOT get pushed, because by default actions which runs from PRs don't have access to secrets like the docker hub password.

**Comment by felipecrs** [comment]
> I thinks we need try to change image to python:slim-bullseye and use https://github.com/BtbN/FFmpeg-Builds

Yeah, this is what Frigate does as well. But Frigate also installs several other dependencies using apt-get which I believe are also necessary. See:

https://github.com/blakeblackshear/frigate/blob/dev/docker/install_deps.sh#L41

We could copy what's done there to make it easier for us.

And about running in Alpine... no clue. But moving to debian isn't too bad. Not so much megabytes more.

**Comment by AlexxIT** [comment]
What the reason to build image on every PR and not push it?

**Comment by AlexxIT** [comment]
It seems that ffmpeg in Debian 12 is very good out of the box.

**Dockerfile**

```
# only debian 12 (bookworm) has latest ffmpeg
FROM debian:bookworm-slim

RUN apt-get -y update && apt-get -y install ffmpeg

CMD [ "sleep", "999d" ]
```

```
Get:223 http://deb.debian.org/debian bookworm/main amd64 ffmpeg amd64 7:5.1.2-1 [1823 kB]
Get:224 http://deb.debian.org/debian bookworm/main amd64 libpciaccess0 amd64 0.17-2 [51.4 kB]
Get:225 http://deb.debian.org/debian bookworm/main amd64 libdrm-intel1 amd64 2.4.114-1 [63.8 kB]
Get:226 http://deb.debian.org/debian bookworm/main amd64 i965-va-driver amd64 2.4.1+dfsg1-1 [309 kB]
Get:227 http://deb.debian.org/debian bookworm/main amd64 libigdgmm12 amd64 22.3.1+ds1-1 [139 kB]
Get:228 http://deb.debian.org/debian bookworm/main amd64 intel-media-va-driver amd64 22.6.3+dfsg1-1 [3189 kB]
Get:229 http://deb.debian.org/debian bookworm/main amd64 libaacs0 amd64 0.11.1-1 [58.4 kB]
Get:230 http://deb.debian.org/debian bookworm/main amd64 libbdplus0 amd64 0.2.0-2 [52.3 kB]
Get:231 http://deb.debian.org/debian bookworm/main amd64 libdecor-0-plugin-1-cairo amd64 0.1.1-1 [19.9 kB]
Get:232 http://deb.debian.org/debian bookworm/main amd64 libgdk-pixbuf2.0-bin amd64 2.42.10+dfsg-1 [17.6 kB]
Get:233 http://deb.debian.org/debian bookworm/main amd64 libglib2.0-data all 2.74.2-1 [1209 kB]
Get:234 http://deb.debian.org/debian bookworm/main amd64 libgpm2 amd64 1.20.7-10+b1 [14.2 kB]
Get:235 http://deb.debian.org/debian bookworm/main amd64 librsvg2-common amd64 2.54.5+dfsg-1 [34.1 kB]
Get:236 http://deb.debian.org/debian bookworm/main amd64 libvdpau-va-gl1 amd64 0.4.2-1+b1 [71.3 kB]
Get:237 http://deb.debian.org/debian bookworm/main amd64 libxcb-randr0 amd64 1.15-1 [117 kB]
Get:238 http://deb.debian.org/debian bookworm/main amd64 mesa-va-drivers amd64 22.2.4-1 [3199 kB]
Get:239 http://deb.debian.org/debian bookworm/main amd64 mesa-vdpau-drivers amd64 22.2.4-1 [3108 kB]
Get:240 http://deb.debian.org/debian bookworm/main amd64 mesa-vulkan-drivers amd64 22.2.4-1 [4807 kB]
Get:241 http://deb.debian.org/debian bookworm/main amd64 pocketsphinx-en-us all 0.8+5prealpha+1-15 [24.3 MB]
Get:242 http://deb.debian.org/debian bookworm/main amd64 va-driver-all amd64 2.16.0-1 [11.8 kB]
Get:243 http://deb.debian.org/debian bookworm/main amd64 vdpau-driver-all amd64 1.5-1 [8720 B]
Get:244 http://deb.debian.org/debian bookworm/main amd64 xdg-user-dirs amd64 0.18-1 [54.4 kB]
```

```
root@6fb5b6365a96:/media# ffmpeg -hide_banner -decoders|grep h264
 VFS..D h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 decoder wrapper (codec h264)
 V....D h264_qsv             H264 video (Intel Quick Sync Video acceleration) (codec h264)
 V..... h264_cuvid           Nvidia CUVID H264 decoder (codec h264)
 
root@6fb5b6365a96:/media# ffmpeg -hide_banner -encoders|grep h264
 V....D libx264              libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
 V....D libx264rgb           libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB (codec h264)
 V....D h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
 V..... h264_omx             OpenMAX IL H.264 video encoder (codec h264)
 V..... h264_qsv             H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (Intel Quick Sync Video acceleration) (codec h264)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 encoder wrapper (codec h264)
 V....D h264_vaapi           H.264/AVC (VAAPI) (codec h264)
 ```

**Comment by felipecrs** [comment]
> What the reason to build image on every PR and not push it?

To test things that could break the build, like changing the Dockerfile.

**Comment by AlexxIT** [comment]
Fail 1:

```
go2rtc-dev_1     | [FATAL tini (7)] exec /run.sh failed: Permission denied
```

Fixed. But fail 2:

```
Step 21/27 : COPY ./docker/run.sh /run.sh
 ---> Using cache
 ---> 87dfbb16f718
Step 22/27 : RUN chmod +x /run.sh
 ---> Running in 8e1833131542
failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```

**Comment by felipecrs** [comment]
You don't need the extra chmod in the Dockerfile, just add the execution permission to git with:

git add --chmod=+x ./run.sh

**Comment by felipecrs** [comment]
Hey, I see the issue. You are trying to build the image in your server, and your server does not have docker buildkit enabled. You should have docker buildkit enabled for the build. Try with:

```
DOCKER_BUILDKIT=1 docker build . -t go2rtc
```

**Comment by AlexxIT** [comment]
No. This is because I unpacker repo.zip on my Windows and copy files to my Linux. Now I downloaded zip to Linux and unpacked there. All ok.

**Comment by felipecrs** [comment]
I'll tell you something cool. You don't need to download anything, just:

```console
docker build https://github.com/felipecrs/go2rtc.git
```

You can also select the branch:

```
docker build https://github.com/felipecrs/go2rtc.git#master
```

Or even the tag v0.1-rc.5 (once one is released with this PR too).

Once you merge it, you will be able to do with your own repo as well.

**Comment by AlexxIT** [comment]
Thanks!

**Pull request merged**
