### PR TITLE
docs(readme): update link for latest binary download method

### PR DESCRIPTION
**Pull request by skrashevich**

### CODE REVIEW

**Comment by AlexxIT** [comment]
I don't know if this site can be trusted. It can push anything to the users at any time

**Comment by felipecrs** [comment]
It's the first time I see nightly.link too, and I found it a great idea.

It's fully open source (https://github.com/oprypin/nightly.link) and its author seems very reputable, given his participation on https://github.com/mkdocs/mkdocs for example.

**Review by AlexxIT — APPROVED** [review]

**Comment by AlexxIT** [comment]
OK, thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.0

**Pull request merged**
