### PR TITLE
Clarify import from go2rtc to hass generic camera

### PR DESCRIPTION
**Pull request by felipecrs**
The protocol is not set by default. According to my tests, only TCP works.

### CODE REVIEW

**Comment by AlexxIT** [comment]
This is not necessary option. Important not to select UDP.

**Comment by felipecrs** [comment]
You are right, I just tested here. Ok, I updated the PR. Can you take a look again, @AlexxIT?

**Comment by AlexxIT** [comment]
Don't think this really necessary, but anyway

**Comment by felipecrs** [comment]
Ok, sorry. I could have closed the PR too. Have a great day/night anyway.

**Pull request merged**
