### PR TITLE
api/streams: added persistency

### PR DESCRIPTION
**Pull request by kottle**
This code updates  streams config file when a  stream is created/deleted with api/streams.

### CODE REVIEW

**Comment by AlexxIT** [comment]
This code totally break my existing YAML config. I think streams should be added to go2rtc.json file, like HomeKit cameras. And go2rtc shouldn't change YAML config from code. Because there is no safe way to do it.

**Comment by felipecrs** [comment]
ESPHome also does something similar, they take YAML files as input and generate JSON files to have them persisted.

**Comment by felipecrs** [comment]
This feature would also come in handy for things like:

- https://github.com/AlexxIT/go2rtc/issues/183

So that streams that gets disabled from API/UI are remembered if go2rtc restarts.

**Comment by AlexxIT** [comment]
I think it's possible to store dynamic part inside `go2rtc.yaml`, but it should be special single line in text format. It will be easy to find and replace. For example:

```yaml
db: '{...}'
```

**Pull request closed without merging**
