### PR TITLE
Nest extend stream

### PR DESCRIPTION
**Pull request by Inrego**
This solves the issue of the stream expiring after 5 minutes.
However, this does not yet make the nest integration stable. If the stream for some reason should expire, any streaming clients will lose connection. And in the case of Frigate, it will consume all available ram within seconds of reconnecting. I've added this disclaimer to the readme.

Locally, I've fixed this as described here:
https://github.com/AlexxIT/go2rtc/issues/723#issuecomment-1872591484

But I don't feel confident committing this change, as I'm unsure if it will break other WebRTC sources.

### CODE REVIEW

**Comment by Inrego** [comment]
Just want to add, that with this PR and the local changes described - my Nest camera has been running rock solid since then on Frigate.

**Comment by T3chArmy** [comment]
This issue has been plaguing me for a while, thanks for your work on this! Hopefully I can stop restarting my frigate server so often and get a bit more life out of my nest cameras.🤞

**Comment by NodeJSmith** [comment]
@AlexxIT just wanted to check on the status of this, I'm having a similar problem with my nest cameras and this seems like it may be the solution

**Comment by T3chArmy** [comment]
I generated a build of 1.8.5 with this cherry picked, and have been running for several weeks. Frigate has been very stable since. 👍

**Comment by Inrego** [comment]
Yeah, same. It's working perfectly.

But the quality is apparently not enough to be merged. The maintainers should remove any mention of nest support until this is fixed imo, since nest does not work in the current state

**Comment by AlexxIT** [comment]
@Inrego Thanks! I made some refactoring to your PR. Unfortunately I don't use Nest to do the testing myself. I hope nothing broke.

I find the Nest APIs to be just plain awful. The whole thing about getting access for $5 and a bunch of tokens is terrible.

**Review by AlexxIT — APPROVED** [review]

**Comment by T3chArmy** [comment]
I have 3 left, and I agree. They're a PITA. They're not perfect, and there are frequent artifacts(mostly due to wifi strength I'm pretty sure). I'm slowly moving away from them, but having this has been a nice stopgap to get a little extra life out of them.

**Comment by NodeJSmith** [comment]
Just switched to the master branch in HA to see if this PR improved things and things are working so much better now, thanks @Inrego and @AlexxIT !

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.0

**Pull request merged**
