### PR TITLE
Added FreeBSD binaries

### PR DESCRIPTION
**Pull request by robvanoostenrijk**
Added go2rtc binaries for FreeBSD aarch64 and amd64 variants.

Binary tested on FreeBSD 13 (amd64)

### CODE REVIEW

**Comment by AlexxIT** [comment]
I think `avfoundation` and `videotoolbox` not related to FreeBSD...

**Comment by robvanoostenrijk** [comment]
Correct. My bad, I had taken the darwin files as a base. I'll remove the MacOS specific elements.

**Comment by AlexxIT** [comment]
Thanks!

**Comment by robvanoostenrijk** [comment]
I saw the FreeBSD binaries weren't there.

Logs say it did compile though.

Working artifact upload:
```
Run actions/upload-artifact@v4
  with:
    name: go[2](https://github.com/AlexxIT/go2rtc/actions/runs/8894698328/job/24423495640#step:25:2)rtc_mac_arm64
    path: go2rtc
    if-no-files-found: warn
    compression-level: 6
    overwrite: false
  env:
    CGO_ENABLED: 0
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Beginning upload of artifact content to blob storage
Uploaded bytes 580[3](https://github.com/AlexxIT/go2rtc/actions/runs/8894698328/job/24423495640#step:25:3)444
Finished uploading artifact content to blob storage!
SHA256 hash of uploaded artifact zip is b9c[4](https://github.com/AlexxIT/go2rtc/actions/runs/8894698328/job/24423495640#step:25:4)5d1e0ce448037f[5](https://github.com/AlexxIT/go2rtc/actions/runs/8894698328/job/24423495640#step:25:5)02fd9d2c6172f66cb17250ac8bb0de0723ee[6](https://github.com/AlexxIT/go2rtc/actions/runs/8894698328/job/24423495640#step:25:6)6c0965a8
Finalizing artifact upload
Artifact go2rtc_mac_arm64.zip successfully finalized. Artifact ID 146036[7](https://github.com/AlexxIT/go2rtc/actions/runs/8894698328/job/24423495640#step:25:7)517
Artifact go2rtc_mac_arm64 has been successfully uploaded! Final size is 5[8](https://github.com/AlexxIT/go2rtc/actions/runs/8894698328/job/24423495640#step:25:8)03444 bytes. Artifact ID is 1460367517
Artifact download URL: https://github.com/AlexxIT/go2rtc/actions/runs/88[9](https://github.com/AlexxIT/go2rtc/actions/runs/8894698328/job/24423495640#step:25:9)4698328/artifacts/1460367517
```

Not working:
```
Run actions/upload-artifact@v3
  with:
    name: go[2](https://github.com/AlexxIT/go2rtc/actions/runs/8894698328/job/24423495640#step:29:2)rtc_freebsd_arm64
    path: go2rtc
    if-no-files-found: warn
  env:
    CGO_ENABLED: 0
With the provided path, there will be 1 file uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "go2rtc_freebsd_arm64" successfully created. Starting upload of file(s)
Total size of all the files uploaded is 5[3](https://github.com/AlexxIT/go2rtc/actions/runs/8894698328/job/24423495640#step:29:3)17932 bytes
File upload process has finished. Finalizing the artifact upload
Artifact has been finalized. All files have been successfully uploaded!

The raw size of all the files that were specified for upload is 13893632 bytes
The size of all the files that were uploaded is 5317932 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage

Note: The size of downloaded zips can differ significantly from the reported size. For more information see: https://github.com/actions/upload-artifact#zipped-artifact-downloads 

Artifact go2rtc_freebsd_arm6[4](https://github.com/AlexxIT/go2rtc/actions/runs/8894698328/job/24423495640#step:29:4) has been successfully uploaded!
```

Perhaps update `actions/upload-artifact@v3` to `actions/upload-artifact@v4`?
That's the only glaring difference I can see.

**Comment by AlexxIT** [comment]
I can see freebsd nightly images
https://nightly.link/AlexxIT/go2rtc/workflows/build/master

**Comment by robvanoostenrijk** [comment]
I can update my fork and see if changing the upload-artifact change triggers it.

**Pull request merged**
