### PR TITLE
BugFix: mdns listener on macOS 

### PR DESCRIPTION
**Pull request by skrashevich**
Fix for #626

### CODE REVIEW

**Comment by OskarLebuda** [comment]
@AlexxIT will this fix our problem with macOS binary?

**Comment by AlexxIT** [comment]
@OskarLebuda maybe. But it will break linux, because it wrong code for this OS :)

**Comment by skrashevich** [comment]
@AlexxIT I don't agree. This syscall is supported on any posix-compatible system, including, of course, linux

**Comment by AlexxIT** [comment]
Some linux versions has another REUSEPORT constant. Some doesn't has it at all
https://stackoverflow.com/questions/14388706/how-do-so-reuseaddr-and-so-reuseport-differ/14388707

**Comment by AlexxIT** [comment]
Thanks. REUSEPORT added with another way, only for macOS

**Pull request closed without merging**
