### PR TITLE
Mention local connection candidate for webrtc

### PR DESCRIPTION
**Pull request by felipecrs**
If my understanding is correct, this is the ideal configuration, am I right?

### CODE REVIEW

**Comment by AlexxIT** [comment]
Local IP will be candidate automatically. Check SDP (response) in browser console.

**Comment by felipecrs** [comment]
Also when running as a container without `--network=host`?

**Comment by AlexxIT** [comment]
Only with this setting. Because without it, go2rtc will not know the IP address of the host

**Comment by felipecrs** [comment]
Do you want me to mention in the README that, if you are running as a docker container without `--network=host`, you should specify the candidate manually? Otherwise I can close the PR.

**Comment by AlexxIT** [comment]
I wouldn't recommend anyone to use docker without network host. This is wrong architect decision in my opinion.

**Comment by felipecrs** [comment]
I see. Thank you.

**Pull request closed without merging**
