### PR TITLE
Backchannel to a Command like ffplay

### PR DESCRIPTION
**Pull request by reifl**
Added support to stream the Backchannel to a command. 
currently hardcoded Codec to PCMA with Clockrate 8000
I've tested it with ffplay:

Example Configuration
```
streams:
    stream:
        - exec:ffmpeg.exe -hide_banner -re -stream_loop -1 -f lavfi -i testsrc=duration=120:size=1280x720:rate=30 -codec:v libx264 -preset:v superfast -tune:v zerolatency -f mpegts -
        - execbc:ffplay.exe -fflags nobuffer -f alaw -ar 8000 -i -
```

### CODE REVIEW

**Comment by gtxaspec** [comment]
awesome!  This is a game changer!  Is it possible to set the sample rate instead of hard coding it?

**Comment by reifl** [comment]
i've tried multiple Codecs and Clockrates but only got the PCMA 8000 to work on my Browsers (Chrome, Firefox, Edge) and the decoder side. I've managed to get RTP Packages with the Opus Codec and a Clockrate of 48000 but cannot decode them with ffplay and don't know how to solve this Problem.

The Clockrate for the Codecs are defined in the RTP Specification i guess (at least i've found them in the RFC Documentation) maybe i'm wrong.

**Comment by skrashevich** [comment]
A very dangerous thingy, both of security and stability

**Comment by AlexxIT** [comment]
Thanks! I've rewritten this PR a bit

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.0

**Pull request merged**
